# Use traditional node_modules instead of Plug'n'Play
nodeLinker: node-modules

# Use project-local cache for isolation
enableGlobalCache: false

# Faster installs with mixed compression
compressionLevel: mixed
