import type { Host } from './types';

export const hosts: Host[] = [
  {
    name: 'Aramis Sennyey',
    title: 'Software Engineer',
    company: 'DoorDash',
    kubecon: 'Atlanta',
    imagePath: '/img/avatars/avatar-aramis-sennyey.jpg',
    linkedinUrl: 'https://www.linkedin.com/in/aramis-sennyey/',
  },
  {
    name: 'Avantika Iyer',
    title: 'Engineering Manager',
    company: 'Spotify',
    kubecon: 'Atlanta',
    imagePath: '/img/avatars/avatar-avantika-iyer.jpg',
    linkedinUrl: 'https://www.linkedin.com/in/avantika-iyer-28414448/',
  },
  {
    name: 'Ben Lambert',
    title: 'Senior Engineer',
    company: 'Spotify',
    kubecon: 'Salt Lake City',
    imagePath: '/img/avatars/avatar-ben-lambert.jpg',
    linkedinUrl: 'https://www.linkedin.com/in/benlambert1/',
  },
  {
    name: 'Bethany Griggs',
    title: 'Senior Software Engineer',
    company: 'Red Hat',
    kubecon: 'London',
    imagePath: '/img/avatars/avatar-bethany-griggs.jpg',
    linkedinUrl: 'https://www.linkedin.com/in/bethgriggs/',
  },
  {
    name: 'Elaine de Mattos Silva Bezerra',
    title: 'Senior Platform Engineer',
    company: 'DB Systel GmbH',
    kubecon: 'Amsterdam',
    imagePath: '/img/avatars/avatar-elaine-de-mattos-silva-bezerra.jpg',
    linkedinUrl: 'https://www.linkedin.com/in/elaine-mattos/',
  },
  {
    name: 'Heikki Hellgren',
    title: 'Expert Lead Developer',
    company: 'OP Financial Group',
    kubecon: 'Amsterdam',
    imagePath: '/img/avatars/avatar-heikki-hellgren.jpg',
    linkedinUrl: 'https://www.linkedin.com/in/heikkihellgren/',
  },
  {
    name: 'Kurt King',
    title: 'Senior Software Engineer',
    company: 'Procore',
    kubecon: 'Atlanta',
    imagePath: '/img/avatars/avatar-kurt-king.jpg',
    linkedinUrl: 'https://www.linkedin.com/in/kurtaking/',
  },
  {
    name: 'Patrik Oldsberg',
    title: 'Senior Engineer',
    company: 'Spotify',
    kubecon: 'Salt Lake City, London, Atlanta',
    imagePath: '/img/avatars/avatar-patrik-oldsberg.jpg',
    linkedinUrl: 'https://www.linkedin.com/in/patrik-oldsberg/',
  },
  {
    name: 'Paul Schultz',
    title: 'Senior Software Engineer',
    company: 'Red Hat',
    kubecon: 'Salt Lake City',
    imagePath: '/img/avatars/avatar-paul-schultz.jpg',
    linkedinUrl: 'https://www.linkedin.com/in/schultzp2020/',
  },
  {
    name: 'Peter Macdonald',
    title: 'Software Engineer',
    company: 'VodafoneZiggo',
    kubecon: 'London',
    imagePath: '/img/avatars/avatar-peter-macdonald.jpg',
    linkedinUrl: 'https://www.linkedin.com/in/peter-j-macdonald/',
  },
  {
    name: 'Vincenzo Scamporlino',
    title: 'Senior Engineer',
    company: 'Spotify',
    kubecon: 'London',
    imagePath: '/img/avatars/avatar-vincenzo-scamporlino.jpg',
    linkedinUrl: 'https://www.linkedin.com/in/vincenzoscamporlino/',
  },
  {
    name: 'Yi Cai',
    title: 'Senior Software Engineer',
    company: 'Red Hat',
    kubecon: 'Salt Lake City',
    imagePath: '/img/avatars/avatar-yi-cai.jpg',
    linkedinUrl: 'https://www.linkedin.com/in/yi-cai/',
  },
  {
    name: 'Andre Wanlin',
    title: 'Customer Success Engineer',
    company: 'Spotify',
    kubecon: 'Salt Lake City, London, Atlanta, Amsterdam',
    imagePath: '/img/avatars/avatar-andre-wanlin.jpg',
    linkedinUrl: 'https://www.linkedin.com/in/andr%C3%A9-wanlin-31a00a16a/',
  },
];
